//! Freeze a snapshot into a re-runnable blueprint (a hand-editable declarative
//! JSON spec, plus an optional standalone shell script), and re-launch it with
//! `anka up`.
//!
//! A blueprint is just a decluttered snapshot — the structure (sessions,
//! windows, panes, cwds, layouts, relaunch commands) without the volatile
//! machine state (pids, scrollback, history counts). Stored under
//! `<anka-dir>/blueprints/<name>.json`, edit it by hand and `anka up <name>` to
//! recreate the layout anywhere.

use anyhow::{bail, Context, Result};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

use crate::model::{Pane, RestoreKind, Snapshot};
use crate::process::shell_quote;
use crate::restore;
use crate::store;

fn blueprints_dir() -> PathBuf {
    store::base_dir().join("blueprints")
}

fn blueprint_json(name: &str) -> PathBuf {
    blueprints_dir().join(format!("{name}.json"))
}

fn blueprint_script(name: &str) -> PathBuf {
    blueprints_dir().join(format!("{name}.sh"))
}

/// Freeze snapshot `name` (default: `last`) into a blueprint of the same name.
pub fn freeze(name: Option<&str>, script: bool) -> Result<()> {
    let src = match name {
        Some(n) => n.to_string(),
        None => store::last_name().context("no snapshot to freeze (no `last`)")?,
    };
    let mut snap = restore::load_snapshot(&src)?;
    declutter(&mut snap);

    fs::create_dir_all(blueprints_dir())?;
    let json = serde_json::to_vec_pretty(&snap)?;
    store::write_atomic(&blueprint_json(&src), &json)?;
    println!(
        "froze '{src}' → blueprint '{src}' ({} sessions)",
        snap.sessions.len()
    );

    if script {
        let path = blueprint_script(&src);
        fs::write(&path, render_script(&snap)).with_context(|| format!("writing {}", path.display()))?;
        let mut perm = fs::metadata(&path)?.permissions();
        perm.set_mode(0o755);
        let _ = fs::set_permissions(&path, perm);
        println!("exported script → {}", path.display());
    }
    Ok(())
}

/// Re-launch a frozen blueprint by name.
pub fn up(name: &str) -> Result<()> {
    if !crate::tmux::server_running() {
        bail!("no tmux server running");
    }
    let path = blueprint_json(name);
    if !path.is_file() {
        bail!(
            "blueprint '{name}' not found (looked in {})",
            blueprints_dir().display()
        );
    }
    let data = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
    let snap: Snapshot =
        serde_json::from_slice(&data).with_context(|| format!("parsing {}", path.display()))?;
    let n = restore::restore_snapshot(&snap)?;
    println!("launched blueprint '{name}' ({n} sessions)");
    Ok(())
}

/// Drop volatile, machine-specific fields so the blueprint is a clean,
/// hand-editable template (no pids, scrollback, or history counts).
fn declutter(snap: &mut Snapshot) {
    snap.client.active_session = None;
    snap.client.last_session = None;
    for s in &mut snap.sessions {
        for w in &mut s.windows {
            for p in &mut w.panes {
                p.pid = 0;
                p.history_size = 0;
                p.contents = None;
            }
        }
    }
}

/// The command to relaunch a pane with in the exported script, or `None`.
fn launch_cmd(p: &Pane) -> Option<String> {
    match p.restore.kind {
        RestoreKind::Shell => None,
        RestoreKind::Process => p.restore.command.clone(),
        RestoreKind::Nvim => Some(p.restore.command.clone().unwrap_or_else(|| "nvim".into())),
    }
}

/// Render a self-contained POSIX shell script that recreates the layout with
/// raw tmux commands — no `anka` needed to run it. Best-effort: pane targeting
/// follows the recorded indices.
fn render_script(snap: &Snapshot) -> String {
    let mut out = String::new();
    out.push_str("#!/bin/sh\n");
    out.push_str("# Generated by `anka freeze --script`. Recreates the tmux layout.\n");
    out.push_str("set -e\n\n");
    for s in &snap.sessions {
        let sq = shell_quote(&s.name);
        let mut windows: Vec<_> = s.windows.iter().collect();
        windows.sort_by_key(|w| w.index);
        for (wi, w) in windows.iter().enumerate() {
            let mut panes: Vec<_> = w.panes.iter().collect();
            panes.sort_by_key(|p| p.index);
            let wname = shell_quote(&w.name);
            let first_cwd = shell_quote(panes.first().map(|p| p.cwd.as_str()).unwrap_or("."));
            if wi == 0 {
                out.push_str(&format!("tmux new-session -d -s {sq} -n {wname} -c {first_cwd}\n"));
            } else {
                out.push_str(&format!("tmux new-window -t {sq} -n {wname} -c {first_cwd}\n"));
            }
            for p in panes.iter().skip(1) {
                out.push_str(&format!("tmux split-window -t {sq} -c {}\n", shell_quote(&p.cwd)));
            }
            if !w.layout.is_empty() {
                out.push_str(&format!(
                    "tmux select-layout -t {sq}:{} {}\n",
                    w.index,
                    shell_quote(&w.layout)
                ));
            }
            for (pi, p) in panes.iter().enumerate() {
                if let Some(cmd) = launch_cmd(p) {
                    out.push_str(&format!(
                        "tmux send-keys -t {sq}:{}.{} {} Enter\n",
                        w.index,
                        pi,
                        shell_quote(&cmd)
                    ));
                }
            }
        }
    }
    out.push_str("\ntmux attach\n");
    out
}
